version: "3.8"

services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: hmdb
      MYSQL_ROOT_PASSWORD: Root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8085:8085"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hmdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Root

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:

